trainer: trainer

dataset:
  src: DATAPATH/ani-1x
  name: ani1x_aug
  size: 1K
  normalize_labels: False

logger:
  name: tensorboard
  project: mdbench

task:
  dataset: lmdb
  description: "Regressing to energies and forces"
  type: regression
  metric: mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True
  task_num: 0
  if_test_final: False

optim:
  delta: 0.05 #5.e-2
  warmup: 0
  augment: True
  max_iter: 40000  #None
  max_epochs: 500 
  if_local: False
  eval_every: 2000
  batch_size: 6
  eval_batch_size: 2 

  force_coefficient: 100 #0
